"""Application layer for the learner practice flow (SPEC-012, SPEC-015, SPEC-022).

The application layer orchestrates the existing learning-domain models into
the first learner-facing vertical slice. It contains no HTML and no
presentation logic: it prepares learner-facing view models for the Web/UI
layer and preserves the domain boundaries established by SPEC-005–011.
SPEC-015 adds the stimulus provider abstraction (external image retrieval
isolated behind an application-level boundary) and the response-aware
evaluator contract.
"""

from .artifact_storage import (
    ARTIFACT_STORAGE_DIR_ENV,
    ArtifactStorage,
    ArtifactStorageError,
    FileArtifactStorage,
    default_artifact_storage_dir,
)
from .artifacts import (
    MAX_SKETCHBOOK_ARTIFACT_BYTES,
    SUPPORTED_SKETCHBOOK_ARTIFACT_TYPES,
    ArtifactRef,
    SketchbookArtifact,
)
from .authoring import (
    DETERMINISTIC_MODEL,
    DETERMINISTIC_PROVIDER,
    FORBIDDEN_FEEDBACK_TERMS,
    AuthoringCandidateStore,
    AuthoringProvenance,
    AuthoringRevision,
    CandidateStatus,
    CandidateValidation,
    PracticeAuthoringBrief,
    PracticeCandidate,
    candidate_from_provider_output,
    draft_candidate_from_brief,
    serialize_candidate,
    validate_candidate,
    with_validation,
)
from .authoring_llm import (
    AuthoringGenerationRequest,
    AuthoringLlmProvider,
    FakeAuthoringProvider,
    LlmGenerationResult,
)
from .demo_data import (
    DEMO_LEARNER_ID,
    GAP_ANALYSIS_PROMPT,
    INTENTION_ACTION_LABEL,
    INTENTION_HEADING,
    INTENTION_PROMPT,
    INTENTION_SKIP_LABEL,
    POST_EVALUATION_PROMPTS,
    PRACTICE_CAPABILITIES,
    PRACTICE_CAPABILITY_ARTICULATE,
    PRACTICE_CAPABILITY_IDEATE,
    PRACTICE_CAPABILITY_INTERPRET,
    PRACTICE_CAPABILITY_OBSERVE,
    PRACTICE_CAPABILITY_REFLECT,
    PRACTICE_MODE_CHOICE_QUESTION,
    REFLECTION_PROMPT,
    REFLECTION_SAVE_LABEL,
    REFLECTION_SKIP_LABEL,
    SHORT_DRILL_ACTIVITY_TITLES,
    STRATEGY_ASSESSMENT_PROMPT,
    build_demo_activities,
    build_demo_activity_map,
    build_demo_skills,
)
from .demo_evaluator import DemoEvaluator, Evaluator
from .errors import (
    ActivityNotFoundError,
    ApplicationError,
    AuthoringProviderConfigurationError,
    AuthoringProviderError,
    CandidateNotApprovableError,
    CandidateNotFoundError,
    CompletionNotFoundError,
    EvaluationFailedError,
    FeedbackNotFoundError,
    InvalidAuthoringBriefError,
    InvalidPracticeResponseError,
    InvalidReflectionResponseError,
    JourneyStateError,
    StimulusRetrievalError,
    SubmissionInProgressError,
    UnknownPracticeModeError,
)
from .practice_continuity import (
    CONTINUATION_ACTION_LABEL,
    CONTINUATION_HEADING,
    PracticeTransition,
    build_practice_transition_map,
    build_practice_transitions,
)
from .practice_modes import (
    PracticeMode,
    PracticeModeDefinition,
    build_practice_mode_definitions,
)
from .stimulus import (
    SUPPORTED_PROVIDERS,
    FallbackDefinition,
    FallbackStimulusProvider,
    ResilientStimulusProvider,
    StimulusProvider,
    WikimediaCommonsProvider,
    build_fallback_stimuli,
    build_stimulus_provider,
)
from .store import (
    Concept,
    DemoActivity,
    LearnerJourneyStore,
    PracticeCompletion,
    PracticeContentContract,
)
from .use_cases import PracticeApplication
from .view_models import (
    CompletionView,
    ContinuationView,
    FeedbackView,
    IntentionView,
    PracticeActivitySummary,
    PracticeActivityView,
    PracticeDashboardView,
    PracticeModeActivitiesView,
    PracticeModeChoiceView,
    PracticeModeOption,
    ReflectionView,
    SketchbookArtifactView,
    StimulusView,
)

__all__ = [
    "ActivityNotFoundError",
    "AuthoringCandidateStore",
    "AuthoringGenerationRequest",
    "AuthoringLlmProvider",
    "AuthoringProvenance",
    "AuthoringRevision",
    "AuthoringProviderConfigurationError",
    "AuthoringProviderError",
    "CandidateNotApprovableError",
    "CandidateNotFoundError",
    "CandidateStatus",
    "CandidateValidation",
    "DETERMINISTIC_MODEL",
    "DETERMINISTIC_PROVIDER",
    "FORBIDDEN_FEEDBACK_TERMS",
    "FakeAuthoringProvider",
    "InvalidAuthoringBriefError",
    "LlmGenerationResult",
    "PracticeAuthoringBrief",
    "PracticeCandidate",
    "PracticeContentContract",
    "candidate_from_provider_output",
    "draft_candidate_from_brief",
    "serialize_candidate",
    "validate_candidate",
    "with_validation",
    "ApplicationError",
    "CompletionNotFoundError",
    "MAX_SKETCHBOOK_ARTIFACT_BYTES",
    "CompletionView",
    "Concept",
    "CONTINUATION_ACTION_LABEL",
    "CONTINUATION_HEADING",
    "DEMO_LEARNER_ID",
    "DemoActivity",
    "DemoEvaluator",
    "EvaluationFailedError",
    "Evaluator",
    "FallbackDefinition",
    "FallbackStimulusProvider",
    "FeedbackNotFoundError",
    "FeedbackView",
    "GAP_ANALYSIS_PROMPT",
    "INTENTION_ACTION_LABEL",
    "INTENTION_HEADING",
    "INTENTION_PROMPT",
    "INTENTION_SKIP_LABEL",
    "IntentionView",
    "InvalidPracticeResponseError",
    "InvalidReflectionResponseError",
    "JourneyStateError",
    "LearnerJourneyStore",
    "POST_EVALUATION_PROMPTS",
    "PRACTICE_CAPABILITIES",
    "PRACTICE_CAPABILITY_ARTICULATE",
    "PRACTICE_CAPABILITY_IDEATE",
    "PRACTICE_CAPABILITY_INTERPRET",
    "PRACTICE_CAPABILITY_OBSERVE",
    "PRACTICE_CAPABILITY_REFLECT",
    "PRACTICE_MODE_CHOICE_QUESTION",
    "PracticeActivitySummary",
    "ARTIFACT_STORAGE_DIR_ENV",
    "ArtifactRef",
    "ArtifactStorage",
    "ArtifactStorageError",
    "FileArtifactStorage",
    "default_artifact_storage_dir",
    "SketchbookArtifact",
    "SketchbookArtifactView",
    "PracticeActivityView",
    "PracticeApplication",
    "PracticeDashboardView",
    "PracticeCompletion",
    "PracticeMode",
    "PracticeModeActivitiesView",
    "PracticeModeChoiceView",
    "PracticeModeDefinition",
    "PracticeModeOption",
    "PracticeTransition",
    "REFLECTION_PROMPT",
    "REFLECTION_SAVE_LABEL",
    "REFLECTION_SKIP_LABEL",
    "ReflectionView",
    "ResilientStimulusProvider",
    "SHORT_DRILL_ACTIVITY_TITLES",
    "STRATEGY_ASSESSMENT_PROMPT",
    "StimulusProvider",
    "StimulusRetrievalError",
    "SUPPORTED_SKETCHBOOK_ARTIFACT_TYPES",
    "StimulusView",
    "SubmissionInProgressError",
    "SUPPORTED_PROVIDERS",
    "UnknownPracticeModeError",
    "WikimediaCommonsProvider",
    "ContinuationView",
    "build_demo_activities",
    "build_demo_activity_map",
    "build_demo_skills",
    "build_fallback_stimuli",
    "build_practice_mode_definitions",
    "build_practice_transition_map",
    "build_practice_transitions",
    "build_stimulus_provider",
]
